update readme with docker compose file sharing information
citizenparker/swsheets pull request #271
Opened 2020-10-16 16:33 UTC by dmccraw

Update readme with Docker information about sharing filesystem directory

2020-10-16 23:47 UTC, duffn requested changes
One nit! Thanks for the PR.

2020-10-16 23:47 UTC, duffn commented on README.md
> +    On the mac you can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
Can we call this "macOS" instead of "the mac"? 😂

2020-10-19 14:38 UTC, dmccraw commented
@duffn Done

2020-10-19 15:18 UTC, duffn approved these changes

2020-10-19 15:18 UTC, merged